spring.application.name=backend


# MongoDB Database Connection
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=watchapi

# JWT Configuration
jwt.secret=9a4f4e35455ad4c1729cc6ea12e52e4242e12e52e4242e12e52e4242e12e52e4
jwt.expiration=3600000

