spring.application.name=backend
server.port=${SERVER_PORT:8081}


# MongoDB Database Connection
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=watchapi

# JWT Configuration
jwt.expiration=3600000
jwt.secret=${JWT_SECRET:0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF}

bakong.token=${BAKONG_TOKEN:}
bakong.account-id=${BAKONG_ACCOUNT_ID:}
bakong.account-name=${BAKONG_ACCOUNT_NAME:}
bakong.merchant-id=${BAKONG_MERCHANT_ID:}
